# Default to using tmux
if [[ "$TERM" != "screen-256color"  ]] && hash tmux 2>/dev/null; then
  tmux attach-session -t "$USER" || tmux new-session -s "$USER"
  exit
fi

# source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ]; then
  source "${HOME}/.bashrc"
fi
