# ~/.bashrc: executed by bash(1) for non-login interactive shells

[ -f "${HOME}/.base_interactive" ] && source "${HOME}/.base_interactive"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
. "$HOME/.cargo/env"
