# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
#export LS_OPTIONS='--color=auto'
#eval "`dircolors`"
#alias ls='ls $LS_OPTIONS'
#alias ll='ls $LS_OPTIONS -l'
#alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

set -o vi

if [ -f "${HOME}/.bash_aliases" ]; then
  source "${HOME}/.bash_aliases"
fi

if [ -f "${HOME}/.bash_functions" ]; then
  source "${HOME}/.bash_functions"
fi

if [ -f "${HOME}/.dirs" ]; then
  source "${HOME}/.dirs"
fi

alias bashrc='vi ~/.bashrc && source ~/.bashrc'

#Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/bin" ] ; then
  PATH="${HOME}/bin:${PATH}"
fi

if [ -f "${HOME}/.bash_completions" ]; then
  source "${HOME}/.bash_completions"
fi

export EDITOR=vim

export XDG_CONFIG_HOME=${HOME}/.config

export PATH="${PATH}:/usr/local/bin:${HOME}/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # use coreutils
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export VISUAL=vim
export EDITOR="$VISUAL"

## Powerline bash
export POWERLINE_CONFIG_COMMAND=/usr/local/bin/powerline-config
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
powerline_sh=/usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

[ -f ${powerline_sh} ] && source ${powerline_sh}

travis_sh=${HOME}/.travis/travis.sh && [ -f ${travis_sh} ] && source ${travis_sh}
j_sh=/usr/local/etc/profile.d/autojump.sh && [ -f ${j_sh} ] && source ${j_sh}

