# ~/.bash_profile is executed for login interactive shells
# This means that .bash_profile is great for commands that should run only once and .bashrc for
# commands that should run every time you start a new shell.

# Default to using tmux
if [[ "$TERM" != "screen-256color"  ]] && hash tmux 2>/dev/null; then
  tmux attach-session -t "$USER" || tmux new-session -s "$USER"
  exit
fi

[ -f "${HOME}/.path_environment" ] && source "${HOME}/.path_environment"

# source the users bashrc if it exists
if [ -f "${HOME}/.bashrc" ]; then
  source "${HOME}/.bashrc"
fi
. "$HOME/.cargo/env"
