# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
#export LS_OPTIONS='--color=auto'
#eval "`dircolors`"
#alias ls='ls $LS_OPTIONS'
#alias ll='ls $LS_OPTIONS -l'
#alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

set -o vi

if [ -f "${HOME}/.bash_aliases" ]; then
  source "${HOME}/.bash_aliases"
fi

if [ -f "${HOME}/.bash_functions" ]; then
  source "${HOME}/.bash_functions"
fi

if [ -f "${HOME}/.dirs" ]; then
  source "${HOME}/.dirs"
fi

#Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/bin" ] ; then
  PATH="${HOME}/bin:${PATH}"
fi

export GPG_TTY=$(tty)

export XDG_CONFIG_HOME=${HOME}/.config

# brew's sbin
export PATH="/usr/local/sbin:$PATH"

# ruby's bin
export PATH="${PATH}:/usr/local/bin:${HOME}/.rvm/bin" # Add RVM to PATH for scripting

# python's bin
export PATH="/usr/local/opt/python/libexec/bin:${PATH}"

# GNU utils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}" # use coreutils
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}"

if [ -f /usr/local/bin/bash ]; then
	export SHELL=/usr/local/bin/bash
else
	export SHELL=/bin/bash
fi

export VISUAL=vim
export EDITOR="${VISUAL}"

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

## Powerline bash
export POWERLINE_CONFIG_COMMAND=/usr/local/bin/powerline-config
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
powerline_sh=/usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

[ -f ${powerline_sh} ] && source ${powerline_sh}

export SCALA_HOME=/usr/local/opt/scala/idea
export GOPATH=$HOME/go
export PATH="${GOPATH}/bin:${PATH}"

if [ -f "${HOME}/.bash_completions" ]; then
  source "${HOME}/.bash_completions"
fi

type jenv >/dev/null 2>&1 && eval "$(jenv init -)"

if [ -n $(find_password slack_user_api_token) ]; then
  export SLACK_USER_API_TOKEN=$(find_password slack_user_api_token)
fi

