# .zlogin is executed for login shells

# Default to using tmux
if [[ "$TERM" != "screen-256color"  ]] && hash tmux 2>/dev/null; then
  tmux attach-session -t "$USER" || tmux new-session -s "$USER"
fi
