#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

logDir=${HOME}/log
[ ! -d ${logDir} ] && mkdir -p ${logDir}

logFile=${logDir}/git-post-commit.log
[ ! -f ${logFile} ] && touch ${logFile}

post-commit-imagesnap >> ${logFile} 2>&1 &

