#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# setup log
logDir=${HOME}/log
[ ! -d ${logDir} ] && mkdir -p ${logDir}

logFile=${logDir}/git-post-commit.log
[ ! -f ${logFile} ] && touch ${logFile}

# say cheese
post-commit-imagesnap >> ${logFile} 2>&1 &

# Generate ctags
.git/hooks/ctags >/dev/null 2>&1 &

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
git lfs post-commit "$@"
