#!/usr/bin/env ruby

# Place this file in ~/.git_template/hooks/post-commit
# Point git to the template directory to import the hook on a git init
#   git config --global init.templatedir '~/.git_template'

# taken from http://stackoverflow.com/a/1320011/818073
def shellescape(str)
    # An empty argument will be skipped, so return empty quotes.
    return "''" if str.empty?

    str = str.dup

    # Process as a single byte sequence because not all shell
    # implementations are multibyte aware.
    str.gsub!(/([^A-Za-z0-9_\-.,:\/@\n])/n, "\\\\\\1")

    # A LF cannot be escaped with a backslash because a backslash + LF
    # combo is regarded as line continuation and simply ignored.
    str.gsub!(/\n/, "'\n'")

    str
end

def snap_picture(file)
  puts "Making gitshot #{file}!"
  output = `imagesnap -q -w 2.5 #{file}`
  puts output
end

def create_file_path
  repo_name=`basename "$(git rev-parse --show-toplevel)"`
  repo_name.chomp!

  home_dir=ENV['HOME']
  git_shots_dir = ENV['GITSHOTS_DIR'] || "#{home_dir}/.gitshots"

  Dir.mkdir(git_shots_dir) unless Dir.exists?(git_shots_dir)

  shellescape("#{git_shots_dir}/#{Time.now.to_i}_#{repo_name}.jpg")
end

unless File.directory?(File.expand_path("../../rebase-merge", __FILE__))
  file = create_file_path
  snap_picture(file)
end

