# ~/.tmuxinator/project.yml

name: geocodio 
root: /Users/grocky/Projects/geocodio/geocodio 

# Get layout with: tmux list-windows -t <session-name> -F "#{window_index}: #{window_layout}"
windows:
  - main:
      layout: 950b,214x56,0,0{107x56,0,0,0,106x56,108,0[106x38,108,0,2,106x17,108,39,12]}
      panes:
        - editor: vim
        - claude: claude-geocodio
        - shell: zsh
  - local-logs:
      panes:
        - dc logs -f geocodio
